# Site settings

title: "Mustering the Mystifying Muses"

author: "David Ray Goforth"

description: "The colorful and misinformed diatribes of a computer-geek-turned-storyologist. Topics include programming, game development, creative writing, table-top RPGs and any other nerd-centric hobbies one might adopt. Stick around, you may get some free stuff!"

biography: "I am a student at <a href='https://www.okbu.edu/'>Oklahoma Baptist University</a>, studying Computer Science and Creative Writing. I have an extensive background in theatre, I have authored a 91k sci-fi novel and am working on a second, and I have roughly 4 years of Dungeon Master experience. You can find my <a href='/assets/Resume.pdf'>Résumé</a>."

colophon: "This website uses the <a href='https://github.com/hugoferreira/papyrus-theme'>Papyrus</a> theme by Hugo Sereno Ferreira.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "https://goandconquer.github.io/"

twitter_username: goandconquer1
github_username: goandconquer
linkedin_username: david-ray-goforth
google-analytics: UA-69060-5

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
